-- HackerRank: https://www.hackerrank.com/AndreyZotov
-- Github: https://github.com/AZ015
-- Author: Andrey Zotov

SELECT
    IF (GRADES.GRADE < 8, CONCAT('NULL'), STUDENTS.NAME),
    GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS
JOIN GRADES
ON STUDENTS.MARKS >= GRADES.MIN_MARK AND STUDENTS.MARKS <= GRADES.MAX_MARK
GROUP BY GRADES.GRADE DESC, STUDENTS.NAME, STUDENTS.MARKS ASC